---
name: Egg-Plugin-Net-Scan
version: 2.01
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: Network host's port is checked.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Egg::Release: 2
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Egg::Plugin::Net::Scan:
    file: lib/Egg/Plugin/Net/Scan.pm
    version: 2.01
  Egg::Plugin::Net::Scan::Result:
    file: lib/Egg/Plugin/Net/Scan.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
